export const PLANTS = [
  { id: 1, name: "Peashooter", type: "offense", cost: 100, damage: "single", range: "long" },
  { id: 2, name: "Sunflower", type: "support", cost: 50, produces: "sun" },
  { id: 3, name: "Cherry Bomb", type: "instant", cost: 150, damage: "area" },
  { id: 4, name: "Wall-nut", type: "defense", cost: 50, durability: "high" },
  { id: 5, name: "Potato Mine", type: "trap", cost: 25, damage: "high" },
  { id: 6, name: "Snow Pea", type: "offense", cost: 175, effect: "slow" },
  { id: 7, name: "Chomper", type: "offense", cost: 150, damage: "instant" },
  { id: 8, name: "Repeater", type: "offense", cost: 200, damage: "double" },

  { id: 9, name: "Puff-shroom", type: "offense", cost: 0, range: "short" },
  { id: 10, name: "Sun-shroom", type: "support", cost: 25, produces: "sun" },
  { id: 11, name: "Fume-shroom", type: "offense", cost: 75, damage: "piercing" },
  { id: 12, name: "Grave Buster", type: "utility", cost: 75 },
  { id: 13, name: "Hypno-shroom", type: "utility", cost: 75, effect: "convert" },
  { id: 14, name: "Scaredy-shroom", type: "offense", cost: 25 },
  { id: 15, name: "Ice-shroom", type: "instant", cost: 75, effect: "freeze_all" },
  { id: 16, name: "Doom-shroom", type: "instant", cost: 125, damage: "massive" },

  { id: 17, name: "Lily Pad", type: "utility", cost: 25 },
  { id: 18, name: "Squash", type: "instant", cost: 50 },
  { id: 19, name: "Threepeater", type: "offense", cost: 325 },
  { id: 20, name: "Tangle Kelp", type: "instant", cost: 25 },
  { id: 21, name: "Jalapeno", type: "instant", cost: 125, damage: "row" },
  { id: 22, name: "Spikeweed", type: "trap", cost: 100 },
  { id: 23, name: "Torchwood", type: "support", cost: 175 },
  { id: 24, name: "Tall-nut", type: "defense", cost: 125 },

  { id: 25, name: "Sea-shroom", type: "offense", cost: 0 },
  { id: 26, name: "Plantern", type: "utility", cost: 25 },
  { id: 27, name: "Cactus", type: "offense", cost: 125 },
  { id: 28, name: "Blover", type: "utility", cost: 100 },
  { id: 29, name: "Split Pea", type: "offense", cost: 125 },
  { id: 30, name: "Starfruit", type: "offense", cost: 125 },
  { id: 31, name: "Pumpkin", type: "defense", cost: 125 },
  { id: 32, name: "Magnet-shroom", type: "utility", cost: 100 },

  { id: 33, name: "Cabbage-pult", type: "offense", cost: 100 },
  { id: 34, name: "Flower Pot", type: "utility", cost: 25 },
  { id: 35, name: "Kernel-pult", type: "offense", cost: 100 },
  { id: 36, name: "Coffee Bean", type: "utility", cost: 75 },
  { id: 37, name: "Garlic", type: "utility", cost: 50 },
  { id: 38, name: "Umbrella Leaf", type: "defense", cost: 100 },
  { id: 39, name: "Marigold", type: "economy", cost: 50 },
  { id: 40, name: "Melon-pult", type: "offense", cost: 300 },

  { id: 41, name: "Gatling Pea", type: "upgrade", cost: 250 },
  { id: 42, name: "Twin Sunflower", type: "upgrade", cost: 150 },
  { id: 43, name: "Gloom-shroom", type: "upgrade", cost: 150 },
  { id: 44, name: "Cattail", type: "upgrade", cost: 225 },
  { id: 45, name: "Winter Melon", type: "upgrade", cost: 200 },
  { id: 46, name: "Gold Magnet", type: "upgrade", cost: 50 },
  { id: 47, name: "Spikerock", type: "upgrade", cost: 125 },
  { id: 48, name: "Cob Cannon", type: "upgrade", cost: 500 },

  { id: 49, name: "Imitater", type: "special", cost: 0 },
];

export const ZOMBIES = [
  {
    id: 1,
    name: "Zombie",
    type: "basic",
    hp: "medium",
    speed: "slow",
  },
  {
    id: 2,
    name: "Flag Zombie",
    type: "basic",
    hp: "medium",
    speed: "slow",
  },
  {
    id: 3,
    name: "Conehead Zombie",
    type: "armored",
    hp: "high",
    speed: "slow",
  },
  {
    id: 4,
    name: "Buckethead Zombie",
    type: "armored",
    hp: "very_high",
    speed: "slow",
  },
  {
    id: 5,
    name: "Pole Vaulting Zombie",
    type: "agile",
    hp: "medium",
    speed: "fast",
    ability: "jump",
  },
  {
    id: 6,
    name: "Newspaper Zombie",
    type: "rage",
    hp: "medium",
    speed: "variable",
    ability: "enrage_on_damage",
  },
  {
    id: 7,
    name: "Screen Door Zombie",
    type: "shield",
    hp: "high",
    speed: "slow",
  },
  {
    id: 8,
    name: "Football Zombie",
    type: "tank",
    hp: "very_high",
    speed: "fast",
  },
  {
    id: 9,
    name: "Dancing Zombie",
    type: "summoner",
    hp: "medium",
    speed: "slow",
    ability: "summon_backup",
  },
  {
    id: 10,
    name: "Backup Dancer",
    type: "minion",
    hp: "low",
    speed: "fast",
  },

  {
    id: 11,
    name: "Ducky Tube Zombie",
    type: "water",
    hp: "medium",
    speed: "slow",
  },
  {
    id: 12,
    name: "Snorkel Zombie",
    type: "water",
    hp: "medium",
    speed: "slow",
    ability: "submerge",
  },
  {
    id: 13,
    name: "Zomboni",
    type: "vehicle",
    hp: "high",
    speed: "slow",
    ability: "ice_trail",
  },
  {
    id: 14,
    name: "Bobsled Team",
    type: "vehicle",
    hp: "medium",
    speed: "fast",
  },

  {
    id: 15,
    name: "Dolphin Rider Zombie",
    type: "agile",
    hp: "medium",
    speed: "fast",
    ability: "jump",
  },
  {
    id: 16,
    name: "Jack-in-the-Box Zombie",
    type: "explosive",
    hp: "medium",
    speed: "slow",
    ability: "random_explosion",
  },
  {
    id: 17,
    name: "Balloon Zombie",
    type: "air",
    hp: "low",
    speed: "fast",
    ability: "fly",
  },
  {
    id: 18,
    name: "Digger Zombie",
    type: "tunnel",
    hp: "medium",
    speed: "slow",
    ability: "rear_attack",
  },
  {
    id: 19,
    name: "Pogo Zombie",
    type: "agile",
    hp: "medium",
    speed: "fast",
    ability: "jump_multiple",
  },

  {
    id: 20,
    name: "Zombie Yeti",
    type: "rare",
    hp: "high",
    speed: "fast",
    ability: "escape",
  },
  {
    id: 21,
    name: "Bungee Zombie",
    type: "special",
    hp: "low",
    speed: "fast",
    ability: "steal_plant",
  },
  {
    id: 22,
    name: "Ladder Zombie",
    type: "utility",
    hp: "medium",
    speed: "slow",
    ability: "place_ladder",
  },
  {
    id: 23,
    name: "Catapult Zombie",
    type: "siege",
    hp: "high",
    speed: "slow",
    ability: "lob_attack",
  },
  {
    id: 24,
    name: "Gargantuar",
    type: "boss",
    hp: "extreme",
    speed: "slow",
    ability: "throw_imp",
  },
  {
    id: 25,
    name: "Imp",
    type: "minion",
    hp: "low",
    speed: "fast",
  },

  {
    id: 26,
    name: "Dr. Zomboss",
    type: "boss",
    hp: "extreme",
    speed: "variable",
    ability: "machine_attacks",
  },
];
