name: Code Quality Check & Publish

on:
  push:
    branches: [main, alpha, beta]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint files
        run: pnpm lint

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Perform type checking
        run: pnpm lint:types

  test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Perform unit test
        run: pnpm test

  publish:
    name: Publish to NPM
    needs: [lint, type-check, test]
    if: github.repository == 'afiiif/floppy-disk' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Update package.json
        run: |
          npm pkg delete 'engines'
          npm pkg delete 'devDependencies'
      - name: Build package
        run: pnpm build
      - name: Release package
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
